using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace TasksAppAPI.Scripts;

public static class GarantirTabelasEmailCampanhaRunner
{
    public static async Task ExecutarAsync(ApplicationDbContext db)
    {
        const string sql = """
        ALTER TABLE "TB_EMAIL_ENVIO_COMERCIAL"
            ADD COLUMN IF NOT EXISTS "EECSTATUSULTIMOENVIO" integer NOT NULL DEFAULT 0;

        ALTER TABLE "TB_EMAIL_ENVIO_COMERCIAL"
            ADD COLUMN IF NOT EXISTS "EECDATAULTIMOENVIO" timestamp with time zone NULL;

        ALTER TABLE "TB_EMAIL_ENVIO_COMERCIAL"
            ADD COLUMN IF NOT EXISTS "EECMENSAGEMERROULTIMO" character varying(1000) NULL;

        ALTER TABLE "TB_EMAIL_ENVIO_COMERCIAL"
            ADD COLUMN IF NOT EXISTS "EECREMETENTEULTIMOENVIO" character varying(255) NULL;

        CREATE TABLE IF NOT EXISTS "TB_EMAIL_CAMPANHA_COMERCIAL" (
            "ECCID" integer GENERATED BY DEFAULT AS IDENTITY,
            "ECCASSUNTO" character varying(500) NOT NULL,
            "ECCCORPOHTML" text NOT NULL,
            "ECCSTATUS" integer NOT NULL DEFAULT 0,
            "ECCDATACRIACAO" timestamp with time zone NOT NULL DEFAULT NOW(),
            "ECCPROXIMOINDICE" integer NOT NULL DEFAULT 0,
            "ECCPAUSAATE" timestamp with time zone NULL,
            "ECCTOTALITENS" integer NOT NULL DEFAULT 0,
            "ECCENVIADOS" integer NOT NULL DEFAULT 0,
            "ECCERROS" integer NOT NULL DEFAULT 0,
            CONSTRAINT "PK_TB_EMAIL_CAMPANHA_COMERCIAL" PRIMARY KEY ("ECCID")
        );

        CREATE TABLE IF NOT EXISTS "TB_EMAIL_CAMPANHA_ITEM" (
            "ECIID" integer GENERATED BY DEFAULT AS IDENTITY,
            "ECCID" integer NOT NULL,
            "EECID" integer NULL,
            "ECIEMAIL" character varying(255) NOT NULL,
            "ECIORDEM" integer NOT NULL,
            "ECISTATUS" integer NOT NULL DEFAULT 0,
            "ECIDATAENVIO" timestamp with time zone NULL,
            "ECIMENSAGEMERRO" character varying(1000) NULL,
            "ECIREMETENTEEMAIL" character varying(255) NULL,
            CONSTRAINT "PK_TB_EMAIL_CAMPANHA_ITEM" PRIMARY KEY ("ECIID"),
            CONSTRAINT "FK_TB_EMAIL_CAMPANHA_ITEM_CAMPANHA"
                FOREIGN KEY ("ECCID") REFERENCES "TB_EMAIL_CAMPANHA_COMERCIAL" ("ECCID") ON DELETE CASCADE,
            CONSTRAINT "FK_TB_EMAIL_CAMPANHA_ITEM_DESTINATARIO"
                FOREIGN KEY ("EECID") REFERENCES "TB_EMAIL_ENVIO_COMERCIAL" ("EECID") ON DELETE SET NULL
        );

        CREATE INDEX IF NOT EXISTS "IX_TB_EMAIL_CAMPANHA_ITEM_ECCID"
            ON "TB_EMAIL_CAMPANHA_ITEM" ("ECCID");
        """;

        await db.Database.ExecuteSqlRawAsync(sql);
    }
}
