using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace TasksAppAPI.Scripts;

public static class GarantirTabelaEmailEnvioComercialRunner
{
    public static async Task ExecutarAsync(ApplicationDbContext db)
    {
        const string sql = """
        CREATE TABLE IF NOT EXISTS "TB_EMAIL_ENVIO_COMERCIAL" (
            "EECID" integer GENERATED BY DEFAULT AS IDENTITY,
            "EECEMAIL" character varying(255) NOT NULL,
            "EECNAOENVIAR" boolean NOT NULL DEFAULT FALSE,
            "EECDATACADASTRO" timestamp with time zone NOT NULL DEFAULT NOW(),
            CONSTRAINT "PK_TB_EMAIL_ENVIO_COMERCIAL" PRIMARY KEY ("EECID")
        );

        CREATE UNIQUE INDEX IF NOT EXISTS "IX_TB_EMAIL_ENVIO_COMERCIAL_EECEMAIL"
            ON "TB_EMAIL_ENVIO_COMERCIAL" ("EECEMAIL");

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20260617142053_CriarTabelaEmailEnvioComercial', '8.0.0')
        ON CONFLICT ("MigrationId") DO NOTHING;
        """;

        await db.Database.ExecuteSqlRawAsync(sql);
    }
}
