using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace TasksAppAPI.Scripts;

public static class GarantirTabelaClienteContratoValorRunner
{
    public static async Task ExecutarAsync(ApplicationDbContext db)
    {
        const string sql = """
        CREATE TABLE IF NOT EXISTS "TB_CLI_CONTRATO_VALOR" (
          "CVCID" integer GENERATED BY DEFAULT AS IDENTITY,
          "CLIID" integer NOT NULL,
          "CVCVALORMENSAL" numeric(18,2) NOT NULL,
          "CVCDATAINICIO" timestamp without time zone NOT NULL,
          "CVCDATAFIM" timestamp without time zone NULL,
          CONSTRAINT "PK_TB_CLI_CONTRATO_VALOR" PRIMARY KEY ("CVCID"),
          CONSTRAINT "FK_TB_CLI_CONTRATO_VALOR_TB_CLI_CLIENTE_CLIID"
            FOREIGN KEY ("CLIID") REFERENCES "TB_CLI_CLIENTE" ("CLIID") ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS "IX_TB_CLI_CONTRATO_VALOR_CLIID"
          ON "TB_CLI_CONTRATO_VALOR" ("CLIID");
        """;

        await db.Database.ExecuteSqlRawAsync(sql);
    }
}

