// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113030120_RenomearNomeParaFantasiaRemoverSobrenome")]
    partial class RenomearNomeParaFantasiaRemoverSobrenome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AnotacaoTarefa", b =>
                {
                    b.Property<int>("AntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ANTID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AntId"));

                    b.Property<string>("AntDescricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ANTDESCRICAO");

                    b.Property<DateTime?>("AntDtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ANTDTCADASTRO");

                    b.Property<int>("TarId")
                        .HasColumnType("integer")
                        .HasColumnName("TARID");

                    b.Property<int>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("USUID");

                    b.HasKey("AntId");

                    b.HasIndex("TarId");

                    b.HasIndex("UsuId");

                    b.ToTable("TB_ANT_ANOTACOES_TAREFAS");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("CliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CLIID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CliId"));

                    b.Property<int>("CliCodigo")
                        .HasColumnType("integer")
                        .HasColumnName("CLICODIGO");

                    b.Property<DateTime?>("CliDataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CLIDATACADASTRO");

                    b.Property<int>("PesId")
                        .HasColumnType("integer")
                        .HasColumnName("PESID");

                    b.HasKey("CliId");

                    b.HasIndex("PesId");

                    b.ToTable("TB_CLI_CLIENTE");
                });

            modelBuilder.Entity("Domain.Entities.Email", b =>
                {
                    b.Property<int>("EmlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("EMLID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmlId"));

                    b.Property<string>("EmlDescricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("EMLDESCRICAO");

                    b.Property<int>("PesId")
                        .HasColumnType("integer")
                        .HasColumnName("PESID");

                    b.HasKey("EmlId");

                    b.HasIndex("PesId");

                    b.ToTable("TB_EMAIL");
                });

            modelBuilder.Entity("Domain.Entities.ImagemTarefa", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IMGID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImgId"));

                    b.Property<byte[]>("ImgArquivo")
                        .HasColumnType("bytea")
                        .HasColumnName("IMGARQUIVO");

                    b.Property<DateTime?>("ImgDataArquivo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("IMGDATAARQUIVO");

                    b.Property<int>("TarId")
                        .HasColumnType("integer")
                        .HasColumnName("TARID");

                    b.HasKey("ImgId");

                    b.HasIndex("TarId");

                    b.ToTable("TB_IMT_IMAGEM_TAREFA");
                });

            modelBuilder.Entity("Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("PesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PESID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PesId"));

                    b.Property<string>("PesDocEstadual")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PESDOCESTADUAL");

                    b.Property<string>("PesDocFederal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PESDOCFEDERAL");

                    b.Property<string>("PesNome")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PESNOME");

                    b.Property<string>("PesSobrenome")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PESSOBRENOME");

                    b.HasKey("PesId");

                    b.ToTable("TB_PESSOA");
                });

            modelBuilder.Entity("Domain.Entities.Tarefa", b =>
                {
                    b.Property<int>("TarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TARID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TarId"));

                    b.Property<int>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("CLIID");

                    b.Property<DateTime?>("TarDtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TARDTCADASTRO");

                    b.Property<DateTime?>("TarDtConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TARDTCONCLUSAO");

                    b.Property<string>("TarProtocolo")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("TARPROTOCOLO");

                    b.Property<string>("TarSolicitante")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("TARSOLICITANTE");

                    b.Property<int>("TarStatus")
                        .HasColumnType("integer")
                        .HasColumnName("TARSTATUS");

                    b.Property<string>("TarTitulo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("TARTITULO");

                    b.Property<int>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("USUID");

                    b.HasKey("TarId");

                    b.HasIndex("CliId");

                    b.HasIndex("UsuId");

                    b.ToTable("TB_TAR_TAREFAS");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("USUID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuId"));

                    b.Property<int>("PesId")
                        .HasColumnType("integer")
                        .HasColumnName("PESID");

                    b.Property<string>("UsuLogin")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("USULOGIN");

                    b.Property<string>("UsuSenha")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("USUSENHA");

                    b.HasKey("UsuId");

                    b.HasIndex("PesId")
                        .IsUnique();

                    b.ToTable("TB_USU_USUARIO");
                });

            modelBuilder.Entity("Domain.Entities.AnotacaoTarefa", b =>
                {
                    b.HasOne("Domain.Entities.Tarefa", "Tarefa")
                        .WithMany("AnotacoesTarefas")
                        .HasForeignKey("TarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("AnotacoesTarefas")
                        .HasForeignKey("UsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Clientes")
                        .HasForeignKey("PesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Domain.Entities.Email", b =>
                {
                    b.HasOne("Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Emails")
                        .HasForeignKey("PesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Domain.Entities.ImagemTarefa", b =>
                {
                    b.HasOne("Domain.Entities.Tarefa", "Tarefa")
                        .WithMany("ImagensTarefa")
                        .HasForeignKey("TarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany("Tarefas")
                        .HasForeignKey("CliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Domain.Entities.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("Domain.Entities.Usuario", "PesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Emails");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Tarefa", b =>
                {
                    b.Navigation("AnotacoesTarefas");

                    b.Navigation("ImagensTarefa");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AnotacoesTarefas");

                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
