// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612141735_AdicionarPlanoContasDuplicata")]
    partial class AdicionarPlanoContasDuplicata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Anotacao", b =>
                {
                    b.Property<int>("AnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ANOID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnoId"));

                    b.Property<string>("AnoDescricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ANODESCRICAO");

                    b.Property<DateTime?>("AnoDtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ANODTCADASTRO");

                    b.Property<string>("AnoLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ANOLINK");

                    b.HasKey("AnoId");

                    b.ToTable("TB_ANO_ANOTACAO");
                });

            modelBuilder.Entity("Domain.Entities.AnotacaoCliente", b =>
                {
                    b.Property<int>("AncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ANCID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AncId"));

                    b.Property<string>("AncDescricao")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("ANCDESCRICAO");

                    b.Property<DateTime?>("AncDtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ANCDTCADASTRO");

                    b.Property<int>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("CLIID");

                    b.HasKey("AncId");

                    b.HasIndex("CliId");

                    b.ToTable("TB_ANC_ANOTACAO_CLIENTE");
                });

            modelBuilder.Entity("Domain.Entities.AnotacaoTarefa", b =>
                {
                    b.Property<int>("AntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ANTID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AntId"));

                    b.Property<string>("AntDescricao")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("ANTDESCRICAO");

                    b.Property<DateTime?>("AntDtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ANTDTCADASTRO");

                    b.Property<int>("TarId")
                        .HasColumnType("integer")
                        .HasColumnName("TARID");

                    b.Property<int>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("USUID");

                    b.HasKey("AntId");

                    b.HasIndex("TarId");

                    b.HasIndex("UsuId");

                    b.ToTable("TB_ANT_ANOTACOES_TAREFAS");
                });

            modelBuilder.Entity("Domain.Entities.CadastroStatusAtendimentoComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SACID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("SACATIVO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("SACDESCRICAO");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("SACNUMERO");

                    b.HasKey("Id");

                    b.ToTable("TB_CAD_STATUS_ATEND_COMERCIAL");
                });

            modelBuilder.Entity("Domain.Entities.CadastroStatusTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("STCID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("STCATIVO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("STCDESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("TB_CAD_STATUS_TAREFA");
                });

            modelBuilder.Entity("Domain.Entities.CadastroTipoAtendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TAID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("TAATIVO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TADESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("TB_CAD_TIPO_ATENDIMENTO");
                });

            modelBuilder.Entity("Domain.Entities.CadastroTipoContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TCID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("TCATIVO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TCDESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("TB_CAD_TIPO_CONTATO");
                });

            modelBuilder.Entity("Domain.Entities.CentroCusto", b =>
                {
                    b.Property<int>("CcuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CCUID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CcuId"));

                    b.Property<int>("EmpId")
                        .HasColumnType("integer")
                        .HasColumnName("EMPID");

                    b.HasKey("CcuId");

                    b.HasIndex("EmpId");

                    b.ToTable("TB_CCU_CENTRO_CUSTO");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("CliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CLIID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CliId"));

                    b.Property<string>("CliCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CLICODIGO");

                    b.Property<DateTime?>("CliDataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CLIDATACADASTRO");

                    b.Property<DateTime?>("CliDataFinalContrato")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CLIDATAFINALCONTRATO");

                    b.Property<int?>("CliDiaNfServico")
                        .HasColumnType("integer")
                        .HasColumnName("CLIDIANFSERVICO");

                    b.Property<int?>("CliDiaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("CLIDIAPAGAMENTO");

                    b.Property<int>("CliStatus")
                        .HasColumnType("integer")
                        .HasColumnName("CLISTATUS");

                    b.Property<decimal?>("CliValorContrato")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CLIVALORCONTRATO");

                    b.Property<int>("PesId")
                        .HasColumnType("integer")
                        .HasColumnName("PESID");

                    b.Property<int>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("USUID");

                    b.HasKey("CliId");

                    b.HasIndex("PesId");

                    b.HasIndex("UsuId");

                    b.ToTable("TB_CLI_CLIENTE");
                });

            modelBuilder.Entity("Domain.Entities.ClienteContratoValor", b =>
                {
                    b.Property<int>("CvcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CVCID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CvcId"));

                    b.Property<int>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("CLIID");

                    b.Property<DateTime?>("CvcDataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CVCDATAFIM");

                    b.Property<DateTime>("CvcDataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CVCDATAINICIO");

                    b.Property<decimal>("CvcValorMensal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CVCVALORMENSAL");

                    b.HasKey("CvcId");

                    b.HasIndex("CliId");

                    b.ToTable("TB_CLI_CONTRATO_VALOR");
                });

            modelBuilder.Entity("Domain.Entities.Das", b =>
                {
                    b.Property<int>("DasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DASID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DasId"));

                    b.Property<DateTime?>("DasDataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DASDATAVENCIMENTO");

                    b.Property<DateTime?>("DasDtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DASDTCADASTRO");

                    b.Property<string>("DasReferencia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DASREFERENCIA");

                    b.Property<int>("DasStatus")
                        .HasColumnType("integer")
                        .HasColumnName("DASSTATUS");

                    b.HasKey("DasId");

                    b.ToTable("TB_DAS");
                });

            modelBuilder.Entity("Domain.Entities.Duplicata", b =>
                {
                    b.Property<int>("DupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DUPID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DupId"));

                    b.Property<int?>("CcuId")
                        .HasColumnType("integer")
                        .HasColumnName("CCUID");

                    b.Property<int?>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("CLIID");

                    b.Property<DateTime>("DupDataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DUPDATAEMISSAO");

                    b.Property<string>("DupDescricaoDespesa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DUPDESCRICAODESPESA");

                    b.Property<int>("DupNumero")
                        .HasColumnType("integer")
                        .HasColumnName("DUPNUMERO");

                    b.Property<int>("DupNumeroParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("DUPNUMEROPARCELAS");

                    b.Property<string>("DupTipo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("DUPTIPO");

                    b.Property<int?>("PlcId")
                        .HasColumnType("integer")
                        .HasColumnName("PLCID");

                    b.HasKey("DupId");

                    b.HasIndex("CcuId");

                    b.HasIndex("CliId");

                    b.HasIndex("PlcId");

                    b.ToTable("TB_DUP_DUPLICATA");
                });

            modelBuilder.Entity("Domain.Entities.Email", b =>
                {
                    b.Property<int>("EmlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("EMLID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmlId"));

                    b.Property<string>("EmlDescricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("EMLDESCRICAO");

                    b.Property<int>("PesId")
                        .HasColumnType("integer")
                        .HasColumnName("PESID");

                    b.HasKey("EmlId");

                    b.HasIndex("PesId");

                    b.ToTable("TB_EMAIL");
                });

            modelBuilder.Entity("Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("EMPID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpId"));

                    b.Property<string>("EmpCnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("EMPCNPJ");

                    b.Property<string>("EmpFantasia")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("EMPFANTASIA");

                    b.Property<string>("EmpRazaoSocial")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("EMPRAZAOSOCIAL");

                    b.HasKey("EmpId");

                    b.ToTable("TB_EMP_EMPRESA");
                });

            modelBuilder.Entity("Domain.Entities.EnvioNotaServico", b =>
                {
                    b.Property<int>("EnsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ENSID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnsId"));

                    b.Property<int>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("CLIID");

                    b.Property<int>("EnsAno")
                        .HasColumnType("integer")
                        .HasColumnName("ENSANO");

                    b.Property<DateTime?>("EnsDataEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ENSDATAENVIO");

                    b.Property<int>("EnsMes")
                        .HasColumnType("integer")
                        .HasColumnName("ENSMES");

                    b.HasKey("EnsId");

                    b.HasIndex("CliId");

                    b.ToTable("TB_ENS_ENVIO_NOTA_SERVICO");
                });

            modelBuilder.Entity("Domain.Entities.ImagemTarefa", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IMGID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImgId"));

                    b.Property<byte[]>("ImgArquivo")
                        .HasColumnType("bytea")
                        .HasColumnName("IMGARQUIVO");

                    b.Property<DateTime?>("ImgDataArquivo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("IMGDATAARQUIVO");

                    b.Property<int>("TarId")
                        .HasColumnType("integer")
                        .HasColumnName("TARID");

                    b.HasKey("ImgId");

                    b.HasIndex("TarId");

                    b.ToTable("TB_IMT_IMAGEM_TAREFA");
                });

            modelBuilder.Entity("Domain.Entities.Parcela", b =>
                {
                    b.Property<int>("ParId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PARID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParId"));

                    b.Property<int>("DupId")
                        .HasColumnType("integer")
                        .HasColumnName("DUPID");

                    b.Property<DateTime?>("ParDataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAR_DATA_PAGAMENTO");

                    b.Property<double>("ParJuros")
                        .HasColumnType("double precision")
                        .HasColumnName("PARJUROS");

                    b.Property<double>("ParMulta")
                        .HasColumnType("double precision")
                        .HasColumnName("PARMULTA");

                    b.Property<int>("ParNumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("PAR_NUMERO_PARCELA");

                    b.Property<string>("ParStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PARSTATUS");

                    b.Property<double>("ParValor")
                        .HasColumnType("double precision")
                        .HasColumnName("PARVALOR");

                    b.Property<DateTime>("ParVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PARVENCIMENTO");

                    b.HasKey("ParId");

                    b.HasIndex("DupId");

                    b.ToTable("TB_PAR_PARCELA");
                });

            modelBuilder.Entity("Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("PesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PESID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PesId"));

                    b.Property<string>("PesDocEstadual")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PESDOCESTADUAL");

                    b.Property<string>("PesDocFederal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PESDOCFEDERAL");

                    b.Property<string>("PesFantasia")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PESFANTASIA");

                    b.HasKey("PesId");

                    b.ToTable("TB_PESSOA");
                });

            modelBuilder.Entity("Domain.Entities.PlanoContas", b =>
                {
                    b.Property<int>("PlcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PLCID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlcId"));

                    b.Property<string>("PlcDescricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("PLCDESCRICAO");

                    b.HasKey("PlcId");

                    b.ToTable("TB_PLC_PLANO_CONTAS");
                });

            modelBuilder.Entity("Domain.Entities.PossivelCliente", b =>
                {
                    b.Property<int>("PocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("POCID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PocId"));

                    b.Property<string>("PocCelDdd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("POCCELDDD");

                    b.Property<string>("PocCelular")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("POCCELULAR");

                    b.Property<string>("PocCnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("POCCNPJ");

                    b.Property<string>("PocCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("POCCODIGO");

                    b.Property<DateTime?>("PocDataImportacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("POCDATAIMPORTACAO");

                    b.Property<DateTime?>("PocDataStatusAtendimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("POC_DATA_STATUS_ATENDIMENTO");

                    b.Property<string>("PocDdd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("POCDDD");

                    b.Property<string>("PocEmailComercial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("POCEMAILCOMERCIAL");

                    b.Property<string>("PocFantasia")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("POCFANTASIA");

                    b.Property<string>("PocLoja")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("POCLOJA");

                    b.Property<string>("PocMotivoPerda")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("POC_MOTIVO_PERDA");

                    b.Property<string>("PocRazaoSocial")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("POCRAZAOSOCIAL");

                    b.Property<string>("PocStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("POCSTATUS");

                    b.Property<int?>("PocStatusAtendimento")
                        .HasColumnType("integer")
                        .HasColumnName("POC_STATUS_ATENDIMENTO");

                    b.HasKey("PocId");

                    b.ToTable("TB_POSSIVEL_CLIENTE");
                });

            modelBuilder.Entity("Domain.Entities.PossivelClienteAnotacao", b =>
                {
                    b.Property<int>("PcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PCAID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PcaId"));

                    b.Property<string>("PcaDescricao")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("PCADESCRICAO");

                    b.Property<DateTime>("PcaDtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PCADTCADASTRO");

                    b.Property<int>("PocId")
                        .HasColumnType("integer")
                        .HasColumnName("POCID");

                    b.Property<int>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("USUID");

                    b.HasKey("PcaId");

                    b.HasIndex("PocId");

                    b.HasIndex("UsuId");

                    b.ToTable("TB_POSSIVEL_CLIENTE_ANOTACAO");
                });

            modelBuilder.Entity("Domain.Entities.Tarefa", b =>
                {
                    b.Property<int>("TarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TARID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TarId"));

                    b.Property<int>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("CLIID");

                    b.Property<string>("TarCelularSolicitante")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TARCELULARSOLICITANTE");

                    b.Property<DateTime?>("TarDtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TARDTCADASTRO");

                    b.Property<DateTime?>("TarDtConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TARDTCONCLUSAO");

                    b.Property<int?>("TarNumero")
                        .HasColumnType("integer")
                        .HasColumnName("TARNUMERO");

                    b.Property<int>("TarPrioridade")
                        .HasColumnType("integer")
                        .HasColumnName("TARPRIORIDADE");

                    b.Property<string>("TarProtocolo")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("TARPROTOCOLO");

                    b.Property<string>("TarSolicitante")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("TARSOLICITANTE");

                    b.Property<int>("TarStatus")
                        .HasColumnType("integer")
                        .HasColumnName("TARSTATUS");

                    b.Property<int?>("TarTipoAtendimento")
                        .HasColumnType("integer")
                        .HasColumnName("TARTIPOATENDIMENTO");

                    b.Property<int?>("TarTipoContato")
                        .HasColumnType("integer")
                        .HasColumnName("TARTIPOCONTATO");

                    b.Property<string>("TarTitulo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("TARTITULO");

                    b.Property<int>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("USUID");

                    b.HasKey("TarId");

                    b.HasIndex("CliId");

                    b.HasIndex("UsuId");

                    b.ToTable("TB_TAR_TAREFAS");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("USUID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuId"));

                    b.Property<int>("PesId")
                        .HasColumnType("integer")
                        .HasColumnName("PESID");

                    b.Property<string>("UsuLogin")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("USULOGIN");

                    b.Property<int>("UsuPerfil")
                        .HasColumnType("integer")
                        .HasColumnName("USUPERFIL");

                    b.Property<string>("UsuSenha")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("USUSENHA");

                    b.HasKey("UsuId");

                    b.HasIndex("PesId")
                        .IsUnique();

                    b.ToTable("TB_USU_USUARIO");
                });

            modelBuilder.Entity("Domain.Entities.AnotacaoCliente", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany("AnotacoesCliente")
                        .HasForeignKey("CliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Domain.Entities.AnotacaoTarefa", b =>
                {
                    b.HasOne("Domain.Entities.Tarefa", "Tarefa")
                        .WithMany("AnotacoesTarefas")
                        .HasForeignKey("TarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("AnotacoesTarefas")
                        .HasForeignKey("UsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.CentroCusto", b =>
                {
                    b.HasOne("Domain.Entities.Empresa", "Empresa")
                        .WithMany("CentrosCusto")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Clientes")
                        .HasForeignKey("PesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.ClienteContratoValor", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany("ContratosValores")
                        .HasForeignKey("CliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Domain.Entities.Duplicata", b =>
                {
                    b.HasOne("Domain.Entities.CentroCusto", "CentroCusto")
                        .WithMany()
                        .HasForeignKey("CcuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CliId");

                    b.HasOne("Domain.Entities.PlanoContas", "PlanoContas")
                        .WithMany()
                        .HasForeignKey("PlcId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CentroCusto");

                    b.Navigation("Cliente");

                    b.Navigation("PlanoContas");
                });

            modelBuilder.Entity("Domain.Entities.Email", b =>
                {
                    b.HasOne("Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Emails")
                        .HasForeignKey("PesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Domain.Entities.EnvioNotaServico", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany("EnviosNotaServico")
                        .HasForeignKey("CliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Domain.Entities.ImagemTarefa", b =>
                {
                    b.HasOne("Domain.Entities.Tarefa", "Tarefa")
                        .WithMany("ImagensTarefa")
                        .HasForeignKey("TarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Domain.Entities.Parcela", b =>
                {
                    b.HasOne("Domain.Entities.Duplicata", "Duplicata")
                        .WithMany("Parcelas")
                        .HasForeignKey("DupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duplicata");
                });

            modelBuilder.Entity("Domain.Entities.PossivelClienteAnotacao", b =>
                {
                    b.HasOne("Domain.Entities.PossivelCliente", "PossivelCliente")
                        .WithMany()
                        .HasForeignKey("PocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PossivelCliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany("Tarefas")
                        .HasForeignKey("CliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Domain.Entities.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("Domain.Entities.Usuario", "PesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Navigation("AnotacoesCliente");

                    b.Navigation("ContratosValores");

                    b.Navigation("EnviosNotaServico");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("Domain.Entities.Duplicata", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Domain.Entities.Empresa", b =>
                {
                    b.Navigation("CentrosCusto");
                });

            modelBuilder.Entity("Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Emails");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Tarefa", b =>
                {
                    b.Navigation("AnotacoesTarefas");

                    b.Navigation("ImagensTarefa");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AnotacoesTarefas");

                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
